#!/bin/bash

echo `date` "debug_message_file/setup_test called (console)."
echo `date` "debug_message_file/setup_test called (debug file)." >> debug.txt

## alreadty installed
# apt-get install openssh-server
## systemctl not found
# systemctl start sshd

# check sshd config file
cat /etc/ssh/sshd_config

